name: Publish caddy image

on:
  push:
    tags:
      - "caddy-v*.*.*"

jobs:
  caddy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract version from tag
        run: |
          TAG="${{ github.ref }}"
          VERSION=${TAG#refs/tags/caddy-v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          context: ./caddy
          file: ./caddy/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/${{ github.repository_owner }}/caddy:${{ env.VERSION }}
            ghcr.io/${{ github.repository_owner }}/caddy:latest
          build-args: |
            VERSION=${{ env.VERSION }}

